name: firstaid2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  geolocator_apple: ^2.3.5
  cupertino_icons: ^1.0.6
  geocoding: ^2.1.1
  what3words: 3.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  http: ^0.13.6
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

platforms:
  macos:
    pluginClass: GeolocatorPlugin


